#!/usr/bin/env python

import os
import sys

sys.path.insert(1, os.path.join(sys.path[0], ".."))

import click
import google.generativeai as genai

import dot_init


@click.group()
def cli():
    pass


@click.command()
@click.option(
    "--file",
    default=None,
    required=True,
    help="file name, relative path",
)
@click.option(
    "--question",
    default=None,
    required=True,
    help="llm question",
)
def question(file: str, question: str) -> dict:
    """ """

    gem_model = genai.GenerativeModel(model_name="gemini-1.5-flash")
    gem_file = genai.upload_file(file)

    gem_response = gem_model.generate_content([question, gem_file])

    print(gem_response.text)